export const CONTENT_DEFAULTS = {
  brand_name: 'Creative Tech Solution BD',
  brand_tagline: 'Empowering Tomorrow with Creative Tech Solutions Today. Serving businesses across Bangladesh since 2020.',
  contact_phone_primary: '+8801784753468',
  contact_phone_secondary: '+8801794517497',
  contact_email: 'creativetechsolutionbd@gmail.com',
  contact_address: 'Biharirpar, Gonopoddy-2151, Nakla, Sherpur, Mymensingh',
  contact_hours: 'Sat-Thu, 9am-7pm',
  whatsapp_number: '8801784753468',
  social_facebook: '#',
  social_linkedin: '#',
  social_youtube: '#',

  home_badge: 'Verified Digital Agency - Sherpur, BD',
  home_hero_title: 'Grow Your Business with Smart Digital Solutions',
  home_hero_highlight: 'Smart Digital',
  home_hero_subtitle: 'We help businesses across Bangladesh build powerful online presence, generate leads, and scale with technology.',
  home_primary_cta: 'Explore Services',
  home_secondary_cta: 'Book a Free Call',
  home_stats: '100+|Happy Clients|Businesses trust us\n500+|Projects Done|Across all services\n95%|Satisfaction|Client success rate\n24/7|Support|Always available',
  home_services_heading: 'Our Services',
  home_services_subtitle: 'Everything your business needs to grow online - delivered under one roof.',
  home_why_heading: 'Why Businesses Choose CreativeTech',
  home_process_heading: 'How It Works',
  home_cta_badge: 'Free Consultation',
  home_cta_title: 'Ready to Grow?',
  home_cta_subtitle: 'Book a free 30-minute call. No commitment - just clarity on how we can help.',

  about_badge: 'About Us',
  about_title: 'We Build Digital Solutions That Actually Work',
  about_highlight: 'Actually Work',
  about_subtitle: 'Founded in 2020, CreativeTechSolutionBD has helped 100+ businesses across Bangladesh grow their digital presence and revenue.',
  about_values_heading: 'Our Values',
  about_team_heading: 'Meet the Team',
  about_journey_heading: 'How We Got Here',

  services_badge: 'What We Offer',
  services_title: 'Our Services',
  services_subtitle: 'Everything your business needs to grow online - delivered under one roof.',
  service_detail_process_heading: 'How It Works',
  service_detail_pricing_heading: 'Pricing Packages',
  service_detail_faq_heading: 'FAQ',
  service_detail_sidebar_title: 'Book This Service',
  service_detail_sidebar_subtitle: "Schedule a free call and we'll walk you through the entire process.",

  portfolio_badge: 'Our Work',
  portfolio_title: 'Real Results for Real Businesses',
  portfolio_highlight: 'Real Results',
  portfolio_subtitle: "Every project has a measurable, verifiable impact on the client's business.",

  contact_badge: 'Get In Touch',
  contact_title: "Let's Talk",
  contact_highlight: 'Talk',
  contact_subtitle: "Have a project in mind? Reach out and we'll reply within 24 hours.",
  contact_success_title: 'Message Sent!',
  contact_success_text: "We'll get back to you within 24 hours.",

  booking_back_label: 'Back to Home',
  booking_title: 'Book a Service',
  booking_subtitle: 'No commitment required - just a conversation.',
  booking_badge: 'Free Consultation',
  booking_success_title: 'Booking Confirmed!',
  booking_success_text: "We'll contact you within 24 hours to confirm your consultation.",

  auth_badge_login: 'Admin access',
  auth_badge_register: 'Create first admin',
  auth_badge_recovery: 'Password recovery',
} as const;

export type ContentKey = keyof typeof CONTENT_DEFAULTS;
export type SiteContent = Record<ContentKey, string>;

export const CONTENT_GROUPS: {
  title: string;
  description: string;
  fields: { key: ContentKey; label: string; multi?: boolean }[];
}[] = [
  {
    title: 'Global Brand & Contact',
    description: 'Header, footer, contact details, and social links.',
    fields: [
      { key: 'brand_name', label: 'Brand Name' },
      { key: 'brand_tagline', label: 'Footer Tagline', multi: true },
      { key: 'contact_phone_primary', label: 'Primary Phone' },
      { key: 'contact_phone_secondary', label: 'Secondary Phone' },
      { key: 'contact_email', label: 'Email' },
      { key: 'contact_address', label: 'Address', multi: true },
      { key: 'contact_hours', label: 'Business Hours' },
      { key: 'whatsapp_number', label: 'WhatsApp Number' },
      { key: 'social_facebook', label: 'Facebook URL' },
      { key: 'social_linkedin', label: 'LinkedIn URL' },
      { key: 'social_youtube', label: 'YouTube URL' },
    ],
  },
  {
    title: 'Home Page',
    description: 'Hero, stats, section headings, and call to action.',
    fields: [
      { key: 'home_badge', label: 'Hero Badge' },
      { key: 'home_hero_title', label: 'Hero Title' },
      { key: 'home_hero_highlight', label: 'Hero Highlight Text' },
      { key: 'home_hero_subtitle', label: 'Hero Subtitle', multi: true },
      { key: 'home_primary_cta', label: 'Primary CTA Label' },
      { key: 'home_secondary_cta', label: 'Secondary CTA Label' },
      { key: 'home_stats', label: 'Stats: value|label|description, one per line', multi: true },
      { key: 'home_services_heading', label: 'Services Heading' },
      { key: 'home_services_subtitle', label: 'Services Subtitle', multi: true },
      { key: 'home_why_heading', label: 'Why Us Heading' },
      { key: 'home_process_heading', label: 'Process Heading' },
      { key: 'home_cta_badge', label: 'CTA Badge' },
      { key: 'home_cta_title', label: 'CTA Title' },
      { key: 'home_cta_subtitle', label: 'CTA Subtitle', multi: true },
    ],
  },
  {
    title: 'About Page',
    description: 'About hero and major section headings.',
    fields: [
      { key: 'about_badge', label: 'Hero Badge' },
      { key: 'about_title', label: 'Hero Title' },
      { key: 'about_highlight', label: 'Highlighted Words' },
      { key: 'about_subtitle', label: 'Hero Subtitle', multi: true },
      { key: 'about_values_heading', label: 'Values Heading' },
      { key: 'about_team_heading', label: 'Team Heading' },
      { key: 'about_journey_heading', label: 'Journey Heading' },
    ],
  },
  {
    title: 'Services Pages',
    description: 'Service listing and service detail shared text.',
    fields: [
      { key: 'services_badge', label: 'Services Badge' },
      { key: 'services_title', label: 'Services Title' },
      { key: 'services_subtitle', label: 'Services Subtitle', multi: true },
      { key: 'service_detail_process_heading', label: 'Detail Process Heading' },
      { key: 'service_detail_pricing_heading', label: 'Detail Pricing Heading' },
      { key: 'service_detail_faq_heading', label: 'Detail FAQ Heading' },
      { key: 'service_detail_sidebar_title', label: 'Detail Sidebar Title' },
      { key: 'service_detail_sidebar_subtitle', label: 'Detail Sidebar Subtitle', multi: true },
    ],
  },
  {
    title: 'Portfolio, Contact, Booking & Auth',
    description: 'Editable text for the remaining public pages.',
    fields: [
      { key: 'portfolio_badge', label: 'Portfolio Badge' },
      { key: 'portfolio_title', label: 'Portfolio Title' },
      { key: 'portfolio_highlight', label: 'Portfolio Highlight' },
      { key: 'portfolio_subtitle', label: 'Portfolio Subtitle', multi: true },
      { key: 'contact_badge', label: 'Contact Badge' },
      { key: 'contact_title', label: 'Contact Title' },
      { key: 'contact_highlight', label: 'Contact Highlight' },
      { key: 'contact_subtitle', label: 'Contact Subtitle', multi: true },
      { key: 'contact_success_title', label: 'Contact Success Title' },
      { key: 'contact_success_text', label: 'Contact Success Text', multi: true },
      { key: 'booking_back_label', label: 'Booking Back Label' },
      { key: 'booking_title', label: 'Booking Title' },
      { key: 'booking_subtitle', label: 'Booking Subtitle', multi: true },
      { key: 'booking_badge', label: 'Booking Badge' },
      { key: 'booking_success_title', label: 'Booking Success Title' },
      { key: 'booking_success_text', label: 'Booking Success Text', multi: true },
      { key: 'auth_badge_login', label: 'Auth Login Badge' },
      { key: 'auth_badge_register', label: 'Auth Register Badge' },
      { key: 'auth_badge_recovery', label: 'Auth Recovery Badge' },
    ],
  },
];
